export type ProductCategory =
  | "Acne Care"
  | "Anti-Ageing & Brightening"
  | "Sun Protection"
  | "Hair Care"
  | "Skin Infections & Anti-Fungal"
  | "Skin Therapy & Wellness"

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  "Acne Care",
  "Anti-Ageing & Brightening",
  "Sun Protection",
  "Hair Care",
  "Skin Infections & Anti-Fungal",
  "Skin Therapy & Wellness",
]

export interface Product {
  id: string
  name: string
  category: ProductCategory
  tagline: string
  description: string
  image: string
  ingredients: string[]
  benefits: string[]
  genericName?: string
  division?: string
  dosageForm?: string
  strength?: string
  composition?: string
  packaging?: string
  storage?: string
  indications?: string[]
  featured?: boolean
  packagingBadge?: string
  certificationBadge?: string
}

export const PRODUCTS: Product[] = [
  // --- Anti-Ageing & Brightening ---
  {
    id: "glybest-12-lotion",
    name: "GLYBEST 12 LOTION",
    category: "Anti-Ageing & Brightening",
    tagline: "High-potency exfoliation & cellular renewal lotion",
    description: "Formulated with 12% Glycolic Acid to promote gentle chemical exfoliation, smooth skin texture, and accelerate cell turnover.",
    image: "/products/glybest-12-lotion.png",
    ingredients: ["Glycolic Acid 12% "],
    benefits: ["Smoothes rough skin texture", "Accelerates cell turnover", "Enhances radiance"],
    genericName: "Glycolic Acid 12% Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "50 ML",
    composition: "Glycolic Acid 12% ",
    packaging: "50 ML Bottle",
    storage: "Store below 25°C. Protect from direct light.",
    indications: ["Rough skin texture", "Photo-damaged skin", "Follicular keratosis"]
  },
  {
    id: "glybest-6-lotion",
    name: "GLYBEST 6 LOTION",
    category: "Anti-Ageing & Brightening",
    tagline: "Balanced skin refining & resurfacing lotion",
    description: "Contains 6% Glycolic Acid for mild skin exfoliation and daily maintenance of soft, rejuvenated skin.",
    image: "/products/glybest-6-lotion.png",
    ingredients: ["Glycolic Acid 6% "],
    benefits: ["Gentle resurfacing", "Improves skin tone", "Hydrating exfoliation"],
    genericName: "Glycolic Acid 6% Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "50 ML",
    composition: "Glycolic Acid 6% ",
    packaging: "50 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Daily skin maintenance", "Mild hyperkeratosis"]
  },
  {
    id: "glybest-12-face-serum",
    name: "GLYBEST-12 FACE SERUM",
    category: "Anti-Ageing & Brightening",
    tagline: "Intensive resurfacing facial serum",
    description: "Concentrated 12% Glycolic Acid facial serum for targeted anti-ageing, glow restoration, and pore refinement.",
    image: "/products/Glybest-12-face.png",
    ingredients: ["Glycolic Acid 12%"],
    benefits: ["Targeted pore refinement", "Boosts luminous glow", "Evens micro-relief"],
    genericName: "Glycolic Acid 12% Serum",
    division: "Dermatology",
    dosageForm: "Serum",
    strength: "30 ML",
    composition: "Glycolic Acid 12%",
    packaging: "30 ML Dropper Bottle",
    storage: "Store in a cool, dry place.",
    indications: ["Fine lines", "Dull skin", "Uneven texture"]
  },
  {
    id: "glybest-3-face-serum",
    name: "GLYBEST-3 FACE SERUM",
    category: "Anti-Ageing & Brightening",
    tagline: "Starter AHA rejuvenating serum",
    description: "Low-dose 3% Glycolic Acid serum designed for sensitive skin or individuals initiating AHA rejuvenation therapy.",
    image: "/products/Glybest-3.png",
    ingredients: ["Glycolic Acid 3%"],
    benefits: ["Ultra-gentle exfoliation", "Suitable for sensitive skin", "Improves clarity"],
    genericName: "Glycolic Acid 3% Serum",
    division: "Dermatology",
    dosageForm: "Serum",
    strength: "30 ML",
    composition: "Glycolic Acid 3%",
    packaging: "30 ML Dropper Bottle",
    storage: "Store below 25°C.",
    indications: ["Sensitive skin exfoliation", "Initial AHA therapy"]
  },
  {
    id: "glybest-6-face-serum",
    name: "GLYBEST-6 FACE SERUM",
    category: "Anti-Ageing & Brightening",
    tagline: "Intermediate skin renewing serum",
    description: "6% Glycolic Acid serum balancing active resurfacing with optimal dermal comfort.",
    image: "/products/Glybest-6-face.png",
    ingredients: ["Glycolic Acid 6%"],
    benefits: ["Refines skin texture", "Enhances brightness", "Maintains barrier balance"],
    genericName: "Glycolic Acid 6% Serum",
    division: "Dermatology",
    dosageForm: "Serum",
    strength: "30 ML",
    composition: "Glycolic Acid 6%",
    packaging: "30 ML Dropper Bottle",
    storage: "Store in a cool, dry place.",
    indications: ["Moderate skin dullness", "Early fine lines"]
  },
  {
    id: "pynomax-tx-face-serum",
    name: "PYNOMAX-TX FACE SERUM",
    category: "Anti-Ageing & Brightening",
    tagline: "Multi-action antioxidant & brightening complex",
    description: "Synergistic serum blending Glutathione, Vitamin C, Hyaluronic Acid, and Niacinamide to defend against photo-ageing.",
    image: "/products/pynomax-tx-face.png",
    ingredients: ["Glutathione", "3-O-Ethyl Ascorbic Acid", "Hyaluronic Acid", "Niacinamide", "Aloe Vera"],
    benefits: ["Potent antioxidant defense", "Plumps skin moisture", "Restores youthful glow"],
    genericName: "Glutathione & Vitamin C Complex Serum",
    division: "Dermatology",
    dosageForm: "Serum",
    strength: "30 ML",
    composition: "Glutathione, 3-O-Ethyl Ascorbic Acid, Hyaluronic Acid, Niacinamide, Aloe Vera",
    packaging: "30 ML Dropper Bottle",
    storage: "Store below 25°C. Keep away from light.",
    indications: ["Photo-ageing", "Environmental oxidative stress", "Dullness"]
  },

  {
    id: "pynomax-tx-cream-20gm",
    name: "PYNOMAX-TX CREAM 20 GM",
    category: "Anti-Ageing & Brightening",
    tagline: "Targeted depigmenting & anti-melasma cream",
    description: "Advanced formulation featuring Tranexamic Acid, Kojic Acid, Niacinamide, and Arbutin for fading dark spots.",
    image: "/products/pynomax-tx.png",
    ingredients: ["Tranexamic Acid", "Niacinamide", "Ginseng Extract", "Allantoin", "Arbutin", "Kojic Acid Dipalmitate"],
    benefits: ["Inhibits melanin synthesis", "Fades dark spots", "Calms skin redness"],
    genericName: "Tranexamic Acid & Kojic Acid Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "20 GM",
    composition: "Tranexamic Acid, Niacinamide, Ginseng Extract, Allantoin, Arbutin, Kojic Acid Dipalmitate",
    packaging: "20 GM Tube",
    storage: "Store below 25°C. Do not freeze.",
    indications: ["Melasma", "Chloasma", "Post-inflammatory hyperpigmentation"]
  },
  {
    id: "pynomax-tx-cream-30gm",
    name: "PYNOMAX-TX CREAM 30 GM",
    category: "Anti-Ageing & Brightening",
    tagline: "Multi-pathway spot corrector cream",
    description: "Extended 30 GM pack of Tranexamic Acid and Kojic Acid Dipalmitate for persistent hyperpigmentation management.",
    image: "/products/pynomax-tx-30ml.png",
    ingredients: ["Tranexamic Acid", "Niacinamide", "Ginseng Extract", "Allantoin", "Arbutin", "Kojic Acid Dipalmitate"],
    benefits: ["Targeted pigmentation repair", "Soothes irritated skin", "Evens blotchy tone"],
    genericName: "Tranexamic Acid & Kojic Acid Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "30 GM",
    composition: "Tranexamic Acid, Niacinamide, Ginseng Extract, Allantoin, Arbutin, Kojic Acid Dipalmitate",
    packaging: "30 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Refractory hyperpigmentation", "Sun spots"]
  },
  {
    id: "pynomax-od-p-tablets",
    name: "PYNOMAX-OD P TABLETS",
    category: "Anti-Ageing & Brightening",
    tagline: "Systemic photoprotective & depigmenting oral care",
    description: "Oral combination of Tranexamic Acid 500mg and Pine Bark Extract 150mg to suppress internal vascular pigmentation signals.",
    image: "/products/pynomax-od-p-tab.png",
    ingredients: ["Tranexamic Acid 500 mg", "Pine Bark Extract 150 mg"],
    benefits: ["Blocks systemic melasma triggers", "Reduces capillary hyperactivity", "High antioxidant support"],
    genericName: "Tranexamic Acid & Pine Bark Extract Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Tranexamic Acid - 500 mg + Pine Bark Extract - 150 mg",
    packaging: "10 Tablets Strip",
    storage: "Store protected from moisture and light."
  },
  {
    id: "pynomax-od-tab",
    name: "PYNOMAX-OD TAB",
    category: "Anti-Ageing & Brightening",
    tagline: "High-strength systemic anti-pigmentation therapy",
    description: "Tranexamic Acid 500 mg once-daily oral tablets for controlling refractory dermal melasma.",
    image: "/products/pynomax-od-tab.png",
    ingredients: ["Tranexamic Acid 500 mg"],
    benefits: ["Inhibits plasminogen activation", "Decreases melanocyte hyperactivity"],
    genericName: "Tranexamic Acid 500 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Tranexamic Acid - 500 mg",
    packaging: "10 Tablets Strip",
    storage: "Store below 30°C."
  },
  {
    id: "pynomax-plus-tablet",
    name: "PYNOMAX-PLUS TABLET",
    category: "Anti-Ageing & Brightening",
    tagline: "Synergistic systemic skin radiance formulation",
    description: "Oral formula combining Tranexamic Acid IP 250 mg with Pine Bark Extract 75 mg for maintenance therapy.",
    image: "/products/pynomax-plus-tab.png",
    ingredients: ["Tranexamic Acid IP 250 mg", "Pine Bark Extract 75 mg"],
    benefits: ["Maintains clear skin tone", "Reduces UV-induced pigmentation"],
    genericName: "Tranexamic Acid & Pine Bark Extract Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Tranexamic Acid IP - 250 mg + Pine Bark Extract - 75 mg",
    packaging: "10 Tablets Strip",
    storage: "Store in a dry place."
  },
  {
    id: "pynomax-tx-tablet-new",
    name: "PYNOMAX-TX TABLET (NEW)",
    category: "Anti-Ageing & Brightening",
    tagline: "Standardized systemic depigmenting oral treatment",
    description: "Tranexamic Acid IP 250 mg tablets for target-specific systemic management of hypermelanosis.",
    image: "/products/pynomax-tx-tab.png",
    ingredients: ["Tranexamic Acid IP 250 mg"],
    benefits: ["Targeted systemic action", "Reduces stubborn pigmentation"],
    genericName: "Tranexamic Acid IP 250 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Tranexamic Acid IP - 250 mg",
    packaging: "10 Tablets Strip",
    storage: "Store below 25°C."
  },
  {
    id: "grazia-up-cream",
    name: "GRAZIA UP CREAM",
    category: "Anti-Ageing & Brightening",
    tagline: "Nourishing depigmenting skin renewal cream",
    description: "Combines Kojic Acid, Arbutin, Niacinamide, AHA, and Squalene to lighten dark spots while deeply moisturizing.",
    image: "/products/grazia up.png",
    ingredients: ["Kojic Acid", "Squalene", "Vitamin E", "Allantoin", "Arbutin", "Niacinamide", "Alpha Hydroxy Acid"],
    benefits: ["Brightens complexion", "Replenishes skin lipid barrier", "Smooths skin tone"],
    genericName: "Kojic Acid & Arbutin Skin Rejuvenating Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "30 GM",
    composition: "Kojic Acid, Squalene, Vitamin E, Allantoin, Arbutin, Niacinamide, Alpha Hydroxy Acid",
    packaging: "30 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Uneven skin tone", "Dry hyperpigmented skin"]
  },
  {
    id: "grazia-up-face-serum",
    name: "GRAZIA UP FACE SERUM",
    category: "Anti-Ageing & Brightening",
    tagline: "Multi-active tone correcting serum",
    description: "Potent blend of Tranexamic Acid, Ferulic Acid, Butyl Resorcinol, Kojic Acid, and p-Terowhite for comprehensive clarity.",
    image: "/products/Grazia-up-gold-30.png",
    ingredients: ["Tranexamic Acid", "Ferulic Acid", "Butyl Resorcinol", "Kojic Acid", "Vitamin E", "p-Terowhite", "Glycolic Acid"],
    benefits: ["Inhibits tyrosinase activity", "Neutralizes free radicals", "Enhances brightness"],
    genericName: "Multi-Active Depigmenting Serum",
    division: "Dermatology",
    dosageForm: "Serum",
    strength: "30 ML",
    composition: "Tranexamic Acid, Ferulic Acid, Butyl Resorcinol, Kojic Acid, Vitamin E, p-Terowhite, Glycolic Acid",
    packaging: "30 ML Dropper Bottle",
    storage: "Store in a cool dark place.",
    indications: ["頑固 dark spots", "Freckles", "Post-acne marks"]
  },
  {
    id: "grazia-up-gold-serum",
    name: "GRAZIA UP GOLD SERUM",
    category: "Anti-Ageing & Brightening",
    tagline: "Luxury hyper-radiance & corrective serum",
    description: "Premium 50 ML advanced depigmenting complex featuring concentrated Ferulic Acid and Butyl Resorcinol for luminous skin.",
    image: "/products/Grazia-up-gold-50.png",
    ingredients: ["Tranexamic Acid", "Ferulic Acid", "Butyl Resorcinol", "Kojic Acid", "Vitamin E", "p-Terowhite", "Glycolic Acid"],
    benefits: ["Deep-penetrating tone correction", "Restores luminous skin reflection", "Prevents recurring spots"],
    genericName: "Gold Standard Depigmenting Serum",
    division: "Dermatology",
    dosageForm: "Serum",
    strength: "50 ML",
    composition: "Tranexamic Acid, Ferulic Acid, Butyl Resorcinol, Kojic Acid, Vitamin E, p-Terowhite, Glycolic Acid",
    packaging: "50 ML Pump Bottle",
    storage: "Store below 25°C.",
    indications: ["Stubborn hyperpigmentation", "Sun damaged skin", "Age spots"],
    featured: true
  },

  // --- Acne Care ---
  {
    id: "nax-face-wash",
    name: "NAX FACE WASH",
    category: "Acne Care",
    tagline: "Purifying anti-bacterial cleanser",
    description: "Enriched with Alum, Tea Tree Oil, Allantoin, and Vitamin E to clear excess sebum and soothe acne-prone skin.",
    image: "/products/nax-face.png",
    ingredients: ["Alum", "Allantoin", "Vitamin E", "Tea Tree Oil"],
    benefits: ["Clears pore-clogging sebum", "Antiseptic Tea Tree protection", "Non-stripping formula"],
    genericName: "Tea Tree Oil & Alum Cleanser",
    division: "Dermatology",
    dosageForm: "Face Wash",
    strength: "75 ML",
    composition: "Alum, Allantoin, Vitamin E, Tea Tree Oil",
    packaging: "75 ML Squeeze Tube",
    storage: "Store below 30°C.",
    indications: ["Acne-prone skin", "Oily complexion", "Surface impurities"]
  },
  {
    id: "nax-gel",
    name: "NAX GEL",
    category: "Acne Care",
    tagline: "Triple-action anti-acne therapy",
    description: "Combines Clindamycin 1%, Niacinamide 4%, and Allantoin 0.1% to eradicate acne pathogens and soothe inflammation.",
    image: "/products/nax gel.png",
    ingredients: ["Clindamycin 1%  ", "Niacinamide 4%  ", "Allantoin 0.1%  "],
    benefits: ["Destroys P. acnes bacteria", "Reduces inflammatory redness", "Prevents scarring"],
    genericName: "Clindamycin & Niacinamide Gel",
    division: "Dermatology",
    dosageForm: "Gel",
    strength: "20 GM",
    composition: "Clindamycin 1%   + Niacinamide 4%   + Allantoin 0.1%  ",
    packaging: "20 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Acne vulgaris", "Inflammatory papules", "Pustules"]
  },
  {
    id: "nax-b-gel",
    name: "NAX-B GEL",
    category: "Acne Care",
    tagline: "Dual-synergy anti-microbial acne treatment",
    description: "Clinically validated combination of Clindamycin Phosphate 1% and Benzoyl Peroxide 2.5% for rapid breakout control.",
    image: "/products/Nax-B-gel.png",
    ingredients: ["Clindamycin Phosphate 1.0%  ", "Benzoyl Peroxide 2.5% "],
    benefits: ["Fast-acting lesion reduction", "Comedolytic & antibacterial action", "Prevents bacterial resistance"],
    genericName: "Clindamycin & Benzoyl Peroxide Gel",
    division: "Dermatology",
    dosageForm: "Gel",
    strength: "15 GM",
    composition: "Clindamycin Phosphate 1.0%   + Benzoyl Peroxide 2.5%  ",
    packaging: "15 GM Tube",
    storage: "Store in a refrigerator (2°C - 8°C). Do not freeze.",
    indications: ["Moderate to severe acne", "Refractory acne vulgaris"],
    featured: true
  },

  // --- Hair Care ---
  {
    id: "dutamax-tab",
    name: "DUTAMAX TAB",
    category: "Hair Care",
    tagline: "Targeted 5-alpha reductase inhibitor",
    description: "Dutasteride IP 0.5 mg oral tablets for treating androgenetic alopecia by blocking DHT conversion.",
    image: "/products/dutamax-0.5-tab.png",
    ingredients: ["Dutasteride IP 0.5 mg"],
    benefits: ["Inhibits Type I & II 5-alpha reductase", "Preserves hair follicle count"],
    genericName: "Dutasteride 0.5 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Dutasteride IP - 0.5 mg",
    packaging: "10 Tablets Strip",
    storage: "Store below 30°C. Protect from moisture."
  },
  {
    id: "dutamax-m-tablet",
    name: "DUTAMAX-M TABLET",
    category: "Hair Care",
    tagline: "Oral vasodilation hair growth treatment",
    description: "Minoxidil IP 2.5 mg oral tablets formulated to stimulate micro-circulation around hair roots.",
    image: "/products/dutamax-m-tab.png",
    ingredients: ["Minoxidil IP 2.5 mg"],
    benefits: ["Enhances follicular blood flow", "Extends hair anagen phase"],
    genericName: "Minoxidil 2.5 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Minoxidil IP - 2.5 mg",
    packaging: "10 Tablets Strip",
    storage: "Store below 25°C."
  },
  {
    id: "redo-plus-hair-serum-60ml",
    name: "REDO PLUS HAIR SERUM 60ML",
    category: "Hair Care",
    tagline: "Advanced biomimetic follicle energizer serum",
    description: "Power-packed hair growth serum featuring Redensyl, Procapil, Anagain, and Adenosine to revitalize dormant follicles.",
    image: "/products/redo-plus-hair.png",
    ingredients: ["Adenosine", "Redensyl", "Procapil", "Anagain"],
    benefits: ["Reactivates hair stem cells", "Reduces hair root shedding", "Increases hair strand density"],
    genericName: "Redensyl, Procapil & Anagain Scalp Serum",
    division: "Dermatology",
    dosageForm: "Serum",
    strength: "60 ML",
    composition: "Adenosine, Redensyl, Procapil, Anagain",
    packaging: "60 ML Spray/Dropper Bottle",
    storage: "Store in a cool dry place.",
    indications: ["Hair thinning", "Telogen effluvium", "Follicular weakening"],
    featured: true
  },
  {
    id: "redo-plus-hair-tablets",
    name: "REDO PLUS HAIR TABLETS",
    category: "Hair Care",
    tagline: "Comprehensive hair nutritional supplement",
    description: "Multivitamin, mineral, and amino acid complex tailored specifically for structural hair shaft synthesis.",
    image: "/products/redo-plus-tab.png",
    ingredients: ["Biotin", "Essential Amino Acids", "Zinc", "Iron", "Natural Extracts"],
    benefits: ["Fortifies keratin structure", "Nourishes scalp matrix", "Supports hair anchor strength"],
    genericName: "Hair Nutritional Complex Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X30",
    composition: "Hair Nutritional Tablet",
    packaging: "30 Tablets Container",
    storage: "Store below 25°C.",
    indications: ["Nutritional hair shedding", "Brittle hair", "Poor scalp health"]
  },

  // --- Sun Protection ---
  {
    id: "sunkage-sunscreen",
    name: "SUNKAGE SUNSCREEN",
    category: "Sun Protection",
    tagline: "Mineral-rich soothing sun shield",
    description: "Formulated with Micronized Zinc Oxide 25%, Aloe Vera, and Tocopheryl Acetate for sensitive skin sun protection.",
    image: "/products/sunkage.png",
    ingredients: ["Micronized Zinc Oxide 25%  ", "Carthamus Tinctorius Oil 3.0%  ", "Aloe Vera 2.0%  ", "Tocopheryl Acetate 0.5%  "],
    benefits: ["Physical mineral UV barrier", "Calms sun-exposed skin", "Antioxidant protection"],
    genericName: "Zinc Oxide Physical Sunscreen",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "50 ML",
    composition: "Zinc Oxide (Micronized) 25%   + Carthamus Tinctorius Oil 3.0%   + Aloe Vera 2.0%   + Tocopheryl Acetate 0.5%  ",
    packaging: "50 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Sensitive skin sun care", "Children & adult sun protection"]
  },
  {
    id: "sunkage-pro-sunscreen",
    name: "SUNKAGE PRO SUNSCREEN",
    category: "Sun Protection",
    tagline: "Advanced hybrid UV & HEV light shield",
    description: "High-performance broad-spectrum sunscreen integrating organic filters with Micronized Zinc Oxide and Titanium Dioxide for complete photoprotection.",
    image: "/products/Sunkage-Pro.png",
    ingredients: ["Methoxycinnamate", "Ethylhexyl Triazone", "Zinc Oxide", "Titanium Dioxide", "Iron Oxides"],
    benefits: ["UVA/UVB broad spectrum", "Blue light & HEV protection", "Non-greasy dry touch finish"],
    genericName: "Broad Spectrum Hybrid Sunscreen SPF 50+",
    division: "Dermatology",
    dosageForm: "Cream/Gel",
    strength: "50 ML",
    composition: "Methoxycinnamate, Ethylhexyl Triazone, Zinc Oxide, Titanium Dioxide, Yellow Iron Oxide and Red Iron Oxide",
    packaging: "50 ML Tube",
    storage: "Store below 30°C. Protect from extreme heat.",
    indications: ["Sun protection", "Prevention of photo-ageing", "Post-peel UV defense"],
    featured: true
  },
  // --- Skin Therapy & Wellness ---
  {
    id: "prutrax-lotion-100ml",
    name: "PRUTRAX LOTION 100 ML",
    category: "Skin Therapy & Wellness",
    tagline: "Instant soothing anti-pruritic lotion",
    description: "Therapeutic anti-itch lotion featuring Calamine, Oatmeal, Pramoxine HCl, and Aloe Vera to soothe acute skin irritation.",
    image: "/products/prutrax-lotion.png",
    ingredients: ["Aloe Vera", "Light Liquid Paraffin", "Calamine", "Oatmeal", "Pramoxine Hydrochloride", "Tetrahydrocurcumin"],
    benefits: ["Fast topical itch relief", "Cools irritated skin", "Restores moisture balance"],
    genericName: "Calamine & Pramoxine Hydrochloride Anti-Itch Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "100 ML",
    composition: "Aloe Vera, Light Liquid Paraffin, Calamine, Oatmeal, Pramoxine Hydrochloride, Tetrahydrocurcumin, Propylparaben",
    packaging: "100 ML Bottle",
    storage: "Store below 25°C. Shake well before use.",
    indications: ["Pruritus", "Insect bites", "Urticaria", "Sunburn itch"]
  },
  {
    id: "prutrax-sr-10-tab",
    name: "PRUTRAX-SR 10 TAB",
    category: "Skin Therapy & Wellness",
    tagline: "Sustained-release anti-histamine therapy",
    description: "Hydroxyzine Hydrochloride 10 mg sustained-release tablets for controlling allergic pruritus, chronic urticaria, and eczematous skin irritation.",
    image: "/products/prutrax-sr-10-tab.jpg",
    ingredients: ["Hydroxyzine Hydrochloride 10 mg"],
    benefits: ["Sustained 24h itch control", "Reduces allergic flares", "Controlled-release antihistamine action"],
    genericName: "Hydroxyzine Hydrochloride Sustained Release Tablets 10 mg",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "10 mg",
    composition: "Hydroxyzine Hydrochloride - 10 mg",
    packaging: "10 x 10 Tablets Box",
    storage: "Store protected from light and moisture.",
    indications: ["Allergic rhinitis", "Acute & chronic urticaria", "Eczematous itch", "Dermatosis"],
    featured: true
  },
  {
    id: "prutrax-sr-25-tab",
    name: "PRUTRAX-SR 25 TAB",
    category: "Skin Therapy & Wellness",
    tagline: "Moderate-strength anti-pruritic treatment",
    description: "Hydroxyzine Hydrochloride 25 mg sustained-release tablets with blister pack for severe allergic dermatitis and nocturnal pruritus relief.",
    image: "/products/prutrax-sr-25-tab.jpg",
    ingredients: ["Hydroxyzine Hydrochloride 25 mg"],
    benefits: ["Relieves nocturnal itching", "Calms histamine release", "Targeted anti-pruritic action"],
    genericName: "Hydroxyzine Hydrochloride Sustained Release Tablets 25 mg",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "25 mg",
    composition: "Hydroxyzine Hydrochloride - 25 mg",
    packaging: "10 x 10 Tablets Box (Blister Pack)",
    storage: "Store below 25°C in a dry place.",
    indications: ["Severe pruritus", "Atopic dermatitis flares", "Chronic urticaria"],
    featured: true
  },
  {
    id: "prutrax-sr-50-tab",
    name: "PRUTRAX-SR 50 TAB",
    category: "Skin Therapy & Wellness",
    tagline: "High-potency systemic itch controller",
    description: "Hydroxyzine Hydrochloride 50 mg SR tablets for refractory pruritus and dermatological allergic crises.",
    image: "/products/prutrax-sr-50-tab.jpg",
    ingredients: ["Hydroxyzine Hydrochloride 50 mg"],
    benefits: ["Maximum systemic anti-histamine action", "Prevents itch-scratch cycle"],
    genericName: "Hydroxyzine Hydrochloride Sustained Release Tablets 50 mg",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "50 mg",
    composition: "Hydroxyzine Hydrochloride - 50 mg",
    packaging: "10 x 10 Tablets Box",
    storage: "Store below 30°C.",
    indications: ["Refractory urticaria", "Severe dermatological itch"],
    featured: true
  },
  {
    id: "galbilast-20-tab",
    name: "GALBILAST-20 TAB",
    category: "Skin Therapy & Wellness",
    tagline: "Second-generation non-drowsy anti-histamine",
    description: "Bilastine 20 mg once-daily oral tablets for prompt, non-sedating relief of hives and allergic skin conditions.",
    image: "/products/galbilast-20-tab.jpg",
    ingredients: ["Bilastine 20 mg"],
    benefits: ["Non-drowsy formulation", "Rapid 1-hour onset of action"],
    genericName: "Bilastine Tablets 20 mg",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "20 mg",
    composition: "Bilastine - 20 mg",
    packaging: "10 x 10 Tablets Box",
    storage: "Store in original package.",
    indications: ["Chronic spontaneous urticaria", "Allergic rhinoconjunctivitis"],
    featured: true
  },
  {
    id: "galbilast-40-tab",
    name: "GALBILAST-40 TAB",
    category: "Skin Therapy & Wellness",
    tagline: "Double-strength non-sedating anti-histamine",
    description: "Bilastine 40 mg tablets designed for heavy flare management in recalcitrant skin allergies.",
    image: "/products/galbilast-40-tab.jpg",
    ingredients: ["Bilastine 40 mg"],
    benefits: ["Enhanced anti-histaminic coverage", "Maintains daytime alertness"],
    genericName: "Bilastine Tablets 40 mg",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "40 mg",
    composition: "Bilastine - 40 mg",
    packaging: "10 x 10 Tablets Box",
    storage: "Store below 25°C.",
    indications: ["Recalcitrant urticaria", "Severe allergic reactions"],
    featured: true
  },
  {
    id: "galbilast-m-tab",
    name: "GALBILAST-M TAB",
    category: "Skin Therapy & Wellness",
    tagline: "Dual-pathway anti-allergy combination",
    description: "Synergistic combination of Bilastine 20 mg and Montelukast 10 mg for combined histamine & leukotriene blockade.",
    image: "/products/galbilast-m-tab.jpg",
    ingredients: ["Bilastine 20 mg", "Montelukast Sodium 10 mg"],
    benefits: ["Dual mediator inhibition", "Comprehensive allergy relief"],
    genericName: "Bilastine and Montelukast Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "20 mg / 10 mg",
    composition: "Bilastine - 20 mg + Montelukast Sodium eq. to Montelukast - 10 mg",
    packaging: "10 x 10 Tablets Box",
    storage: "Store in a dry place.",
    indications: ["Allergic dermatosis with respiratory involvement", "Urticaria"],
    featured: true
  },
  {
    id: "galdopin-cream",
    name: "GALDOPIN CREAM",
    category: "Skin Therapy & Wellness",
    tagline: "Targeted topical tricyclic anti-pruritic",
    description: "Doxepin Hydrochloride IP 5%   cream offering potent topical H1 and H2 histamine receptor antagonism.",
    image: "/products/galdopin-cream.png",
    ingredients: ["Doxepin Hydrochloride IP 5%  "],
    benefits: ["Direct topical itch suppression", "Relieves eczematous itching"],
    genericName: "Doxepin Hydrochloride 5% Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "30 GM",
    composition: "Doxepin Hydrochloride IP - 5%  ",
    packaging: "30 GM Tube",
    storage: "Store below 25°C. Do not freeze.",
    indications: ["Moderate pruritus in lichen simplex chronicus", "Atopic dermatitis"]
  },
  {
    id: "galdopin-10-capsules",
    name: "GALDOPIN-10 CAPSULES",
    category: "Skin Therapy & Wellness",
    tagline: "Low-dose systemic itch & tension modulator",
    description: "Doxepin Hydrochloride 10 mg oral capsules for managing systemic dermatological pruritus.",
    image: "/products/galdopin-10.png",
    ingredients: ["Doxepin Hydrochloride 10 mg"],
    benefits: ["Calms central itch perception", "Supports restful sleep"],
    genericName: "Doxepin Hydrochloride Capsules IP 10 mg",
    division: "Dermatology",
    dosageForm: "Capsules",
    strength: "10 mg",
    composition: "Doxepin Hydrochloride - 10 mg",
    packaging: "10 x 10 Capsules Box",
    storage: "Store below 25°C.",
    indications: ["Psychogenic pruritus", "Chronic itching"],
    featured: true
  },
  {
    id: "galdopin-25-capsules",
    name: "GALDOPIN-25 CAPSULES",
    category: "Skin Therapy & Wellness",
    tagline: "Systemic anti-pruritic & neuro-dermatology therapy",
    description: "Doxepin Hydrochloride 25 mg capsules providing systemic control for severe chronic itching.",
    image: "/products/galdopin-25.png",
    ingredients: ["Doxepin Hydrochloride 25 mg"],
    benefits: ["Strong H1 receptor blockade", "Soothes neurogenic itch signals"],
    genericName: "Doxepin Hydrochloride Capsules IP 25 mg",
    division: "Dermatology",
    dosageForm: "Capsules",
    strength: "25 mg",
    composition: "Doxepin Hydrochloride - 25 mg",
    packaging: "10 x 10 Capsules Box",
    storage: "Store protected from light.",
    indications: ["Severe chronic pruritus", "Neurodermatitis"],
    featured: true
  },

  // --- Skin Infections & Anti-Fungal ---
  {
    id: "fusirose-cream",
    name: "FUSIROSE CREAM",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Targeted topical antibacterial cream",
    description: "Fusidic Acid 2%   cream for treating primary and secondary bacterial skin infections caused by Staph and Strep species.",
    image: "/products/fusirose cream.png",
    ingredients: ["Fusidic Acid 2%  "],
    benefits: ["Potent Staphylococcal coverage", "Deep tissue penetration", "Non-staining formulation"],
    genericName: "Fusidic Acid 2% Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "10 GM",
    composition: "Fusidic Acid - 2%  ",
    packaging: "10 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Impetigo", "Infected eczema", "Folliculitis"]
  },
  {
    id: "fusirose-lotion",
    name: "FUSIROSE LOTION",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Fluid topical antibacterial lotion",
    description: "Fusidic Acid 2%  fluid lotion for easy application over hairy or wide-area bacterial skin lesions.",
    image: "/products/fusirose lotion.png",
    ingredients: ["Fusidic Acid 2% "],
    benefits: ["Spreadable over hairy areas", "Rapid absorption"],
    genericName: "Fusidic Acid 2% Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "15 ML",
    composition: "Fusidic Acid - 2% ",
    packaging: "15 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Scalp folliculitis", "Widespread superficial pyoderma"]
  },
  {
    id: "fusirose-b-lotion",
    name: "FUSIROSE-B LOTION",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Dual anti-bacterial & anti-inflammatory lotion",
    description: "Combines Fusidic Acid 2% with Beclomethasone 0.025% to rapidly clear bacterial infection and relieve associated swelling.",
    image: "/products/fusirose-b.png",
    ingredients: ["Fusidic Acid 2% ", "Beclomethasone IP 0.025% "],
    benefits: ["Clears infection while reducing swelling", "Relieves redness and discomfort"],
    genericName: "Fusidic Acid & Beclomethasone Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "15 ML",
    composition: "Fusidic Acid - 2% , Beclomethasone IP - 0.025% ",
    packaging: "15 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Infected inflammatory eczema", "Steroid-responsive dermatosis with bacterial infection"]
  },
  {
    id: "itafast-200-capsules",
    name: "ITAFAST-200 CAPSULES",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Broad-spectrum systemic triazole antifungal",
    description: "Itraconazole BP 200 mg micro-pelletized oral capsules for rapid eradication of systemic and recalcitrant fungal infections.",
    image: "/products/itafast-200.jpg",
    ingredients: ["Itraconazole BP 200 mg"],
    benefits: ["High tissue lipophilicity", "Once-daily therapeutic dosing", "Effective against recalcitrant fungal infections"],
    genericName: "Itraconazole Capsules",
    division: "Dermatology",
    dosageForm: "Capsules",
    strength: "10 x 10 Capsules",
    composition: "Itraconazole BP - 200 mg",
    packaging: "10 x 10 Capsules Box",
    storage: "Store below 25°C. Protect from moisture.",
    indications: ["Tinea corporis", "Tinea cruris", "Onychomycosis", "Systemic candidiasis"]
  },
  {
    id: "itanol-100-capsules",
    name: "ITANOL-100 CAPSULES",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Standard systemic oral antifungal therapy",
    description: "Itraconazole BP 100 mg capsules formulated for effective treatment of superficial dermatophyte infections.",
    image: "/products/itanol-100-tab.png",
    ingredients: ["Itraconazole BP 100 mg"],
    benefits: ["Targeted antimycotic action", "Proven clinical safety profile"],
    genericName: "Itraconazole 100 mg Capsules",
    division: "Dermatology",
    dosageForm: "Capsules",
    strength: "1X10",
    composition: "Itraconazole BP - 100 mg",
    packaging: "10 Capsules Strip",
    storage: "Store in a dry place.",
    indications: ["Superficial mycoses", "Pityriasis versicolor"]
  },
  {
    id: "itanol-200-cap",
    name: "ITANOL-200 CAP",
    category: "Skin Infections & Anti-Fungal",
    tagline: "High-potency systemic antimycotic capsule",
    description: "Itraconazole BP 200 mg capsules providing robust bio-availability against resistant fungal strains.",
    image: "/products/itanol-200-tab.png",
    ingredients: ["Itraconazole BP 200 mg"],
    benefits: ["Superior keratin binding", "Prevents fungal relapse"],
    genericName: "Itraconazole 200 mg Capsules",
    division: "Dermatology",
    dosageForm: "Capsules",
    strength: "1X10",
    composition: "Itraconazole BP - 200 mg",
    packaging: "10 Capsules Strip",
    storage: "Store below 25°C.",
    indications: ["Refractory tinea infections", "Fungal nail infections"]
  },
  {
    id: "lulinol-xl-cream",
    name: "LULINOL XL CREAM",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Next-generation once-daily topical antifungal",
    description: "Luliconazole 1%   cream featuring exceptional fungicidal activity with high retention in the stratum corneum.",
    image: "/products/lulinol-xl-cream.png",
    ingredients: ["Luliconazole 1%  "],
    benefits: ["Fungicidal against dermatophytes", "Once-daily short course convenience", "Rapidly relieves itching"],
    genericName: "Luliconazole 1% Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "50 GM",
    composition: "Luliconazole - 1%  ",
    packaging: "50 GM Tube",
    storage: "Store below 25°C. Do not freeze.",
    indications: ["Tinea pedis (athlete's foot)", "Tinea cruris (jock itch)", "Tinea corporis (ringworm)"],
    featured: true
  },
  {
    id: "terbimax-tablets",
    name: "TERBIMAX TABLETS",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Fungicidal allylamine oral treatment",
    description: "Terbinafine Hydrochloride IP 250 mg tablets offering potent fungicidal inhibition of squalene epoxidase.",
    image: "/products/terbimax-tab.png",
    ingredients: ["Terbinafine Hydrochloride IP 250 mg"],
    benefits: ["Fungicidal action", "Rapid accumulation in hair and nails"],
    genericName: "Terbinafine 250 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X7",
    composition: "Terbinafine Hydrochloride IP - 250 mg",
    packaging: "7 Tablets Blister Strip",
    storage: "Store below 30°C.",
    indications: ["Dermatophyte infections", "Onychomycosis"]
  },
  {
    id: "terbimax-f-cream",
    name: "TERBIMAX-F CREAM",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Dual antifungal & anti-inflammatory cream",
    description: "Combines Terbinafine 1% with Fluticasone 0.05% for treating inflamed fungal infections with intense itching.",
    image: "/products/terbimax-f-cream.png",
    ingredients: ["Fluticasone Propionate IP 0.05%  ", "Terbinafine Hydrochloride IP 1%"],
    benefits: ["Rapid symptom relief", "Eradicates fungal pathogens while soothing inflammation"],
    genericName: "Terbinafine & Fluticasone Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "10 GM",
    composition: "Fluticasone Propionate IP - 0.05%   + Terbinafine Hydrochloride IP - 1%",
    packaging: "10 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Inflammatory tinea cruris", "Tinea corporis with severe eczema"]
  },
  {
    id: "terbimax-f-lotion-15ml",
    name: "TERBIMAX-F LOTION 15 ML",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Fluid antimycotic & anti-inflammatory lotion",
    description: "Terbinafine Hydrochloride 1% and Fluticasone Propionate 0.05% lotion for easy application on wide-spread inflamed fungal infections.",
    image: "/products/terbimax-f-15ml.png",
    ingredients: ["Fluticasone Propionate IP 0.05% w/v", "Terbinafine Hydrochloride IP 1% w/v"],
    benefits: ["Spreads easily over large surfaces", "Rapid relief from fungal itch & redness", "Combined antifungal & anti-inflammatory action"],
    genericName: "Fluticasone & Terbinafine Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "15 ML",
    composition: "Fluticasone Propionate IP 0.05% w/v + Terbinafine Hydrochloride IP 1% w/v",
    packaging: "15 ML Bottle",
    storage: "Store in a cool & dry place. Protect from light. Do not freeze.",
    indications: ["Inflamed tinea corporis", "Intertrigo", "Fungal dermatosis with eczema"]
  },
  {
    id: "terbimax-f-lotion-30ml",
    name: "TERBIMAX-F LOTION 30 ML",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Extended fluid antimycotic therapy",
    description: "30 ML bottle of Terbinafine 1% and Fluticasone 0.05% lotion for persistent or multi-site fungal dermatoses.",
    image: "/products/terbimax-f-30ml.png",
    ingredients: ["Fluticasone Propionate 0.05% ", "Terbinafine Hydrochloride 1% "],
    benefits: ["Comprehensive coverage", "Dual symptom & pathogen control"],
    genericName: "Terbinafine & Fluticasone Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "30 ML",
    composition: "Fluticasone Propionate - 0.05%  + Terbinafine Hydrochloride - 1% ",
    packaging: "30 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Extensive fungal dermatosis"]
  },
  {
    id: "vorifast-200-tab",
    name: "VORIFAST-200 TAB",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Second-generation broad-spectrum triazole",
    description: "Voriconazole IP 200 mg oral tablets for treating severe and invasive fungal infections.",
    image: "/products/vorifast-200.png",
    ingredients: ["Voriconazole IP 200 mg"],
    benefits: ["Potent against resistant Candida & Aspergillus", "High systemic bio-availability"],
    genericName: "Voriconazole 200 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Voriconazole IP - 200 mg",
    packaging: "10 Tablets Strip",
    storage: "Store below 30°C.",
    indications: ["Invasive candidiasis", "Refractory deep mycoses"]
  },

  {
    id: "galo-e-cream",
    name: "GALO-E CREAM",
    category: "Skin Therapy & Wellness",
    tagline: "Botanical lipid-replenishing moisture cream",
    description: "Nourishing barrier cream featuring Aloe Vera 10%, Neem 3%, Tulsi 3%, and Vitamin E 1% for deep epidermal hydration.",
    image: "/products/Galo-E-cream.png",
    ingredients: ["Aloe Vera Juice 10%", "Azadirachta Indica 3%", "Ocimum Sanctum 3%", "Vitamin E 1%"],
    benefits: ["Rich botanical hydration", "Calms sensitive & dry skin", "Antioxidant barrier protection"],
    genericName: "Aloe Vera & Vitamin E Botanical Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "100 GM",
    composition: "Aloe Vera Juice 10% + Azadirachta Indica 3% + Ocimum Sanctum 3% + Vitamin E 1%",
    packaging: "100 GM Jar",
    storage: "Store below 25°C.",
    indications: ["Dry & sensitive skin", "Post-exposure skin recovery", "Daily moisture care"],
    featured: true
  },
  {
    id: "galo-e-lotion",
    name: "GALO-E LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "Lightweight botanical hydrating lotion",
    description: "Fluid lotion format of Aloe Vera 10%, Neem, Tulsi, and Vitamin E for rapid-absorbing body hydration.",
    image: "/products/Galo-e-Lotion.png",
    ingredients: ["Aloe Vera Juice 10%", "Azadirachta Indica 3%", "Ocimum Sanctum 3%", "Vitamin E 1%"],
    benefits: ["Fast-absorbing fluid texture", "Non-sticky daily hydration"],
    genericName: "Aloe Vera & Vitamin E Botanical Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "100 ML",
    composition: "Aloe Vera Juice 10% + Azadirachta Indica 3% + Ocimum Sanctum 3% + Vitamin E 1%",
    packaging: "100 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Body skin dryness", "Daily hydration"]
  },
  {
    id: "pynomax-tx-lotion",
    name: "PYNOMAX-TX LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "Hydrating brightening body lotion",
    description: "Formulated with Tranexamic Acid, Niacinamide, Sodium Hyaluronate, Vitamin C & E for radiant, deeply hydrated skin.",
    image: "/products/pynomax-tx-lotion.png",
    ingredients: ["Tranexamic Acid", "Niacinamide", "Alpha Arbutin", "Sodium Hyaluronate", "Vitamin C", "Vitamin E", "Tangerine Peel Extract", "Glycolic Acid"],
    benefits: ["Deep hyaluronic moisture", "Evens out body skin tone", "Improves skin luminosity"],
    genericName: "Tranexamic Acid & Hyaluronic Hydrating Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "100 ML",
    composition: "Tranexamic Acid, Niacinamide, Alpha Arbutin, Sodium Hyaluronate, Vitamin C, Vitamin E, Citrus Reticulata (Tangerine) Peel Extract, Mulberry Extract, Glycolic Acid",
    packaging: "100 ML Bottle",
    storage: "Store in a cool dry place.",
    indications: ["Uneven body tone", "Dehydrated skin"]
  },

  {
    id: "nuvalcy-1000-tablets",
    name: "NUVALCY-1000 TABLETS",
    category: "Skin Infections & Anti-Fungal",
    tagline: "High-dose oral antiviral therapy",
    description: "Valacyclovir Hydrochloride 1000 mg oral prodrug of Acyclovir for prompt treatment of Herpes Zoster (shingles).",
    image: "/products/nuvalcy-1000.png",
    ingredients: ["Valacyclovir Hydrochloride 1000 mg"],
    benefits: ["Accelerates lesion healing", "Reduces duration of acute post-herpetic neuralgia"],
    genericName: "Valacyclovir 1000 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X3",
    composition: "Valacyclovir Hydrochloride - 1000 mg",
    packaging: "3 Tablets Blister Strip",
    storage: "Store below 25°C. Protect from moisture.",
    indications: ["Herpes Zoster (shingles)", "Severe Herpes Simplex outbreak"]
  },
  {
    id: "nuvalcy-500-tablets",
    name: "NUVALCY-500 TABLETS",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Standard oral antiviral treatment",
    description: "Valacyclovir Hydrochloride 500 mg tablets for acute and suppressive management of Herpes Simplex labialis.",
    image: "/products/nuvalcy-500.png",
    ingredients: ["Valacyclovir Hydrochloride 500 mg"],
    benefits: ["Shortens outbreak duration", "Suppresses recurrent viral shedding"],
    genericName: "Valacyclovir 500 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X3",
    composition: "Valacyclovir Hydrochloride - 500 mg",
    packaging: "3 Tablets Blister Strip",
    storage: "Store below 25°C.",
    indications: ["Herpes labialis (cold sores)", "Recurrent genital herpes"]
  },

  {
    id: "tacroin-forte-lotion",
    name: "TACROVIN FORTE LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "Potent calcineurin inhibitor lotion",
    description: "Tacrolimus Lotion IP 0.1%  for targeted non-steroidal immune-modulation in moderate to severe atopic eczema.",
    image: "/products/Tacrovin-Forte-Lotion.png",
    ingredients: ["Tacrolimus Lotion IP 0.1% "],
    benefits: ["Non-steroidal immune modulation", "No risk of skin atrophy", "Suitable for scalp & hairy regions"],
    genericName: "Tacrolimus 0.1% Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "20 ML",
    composition: "Tacrolimus Lotion IP - 0.1% ",
    packaging: "20 ML Bottle",
    storage: "Store below 25°C. Do not freeze.",
    indications: ["Atopic dermatitis", "Scalp vitiligo", "Steroid-sparing maintenance"]
  },
  {
    id: "tacrovin-forte-oint-10gm",
    name: "TACROVIN FORTE OINT. 10GM",
    category: "Skin Therapy & Wellness",
    tagline: "High-strength calcineurin inhibitor ointment",
    description: "Tacrolimus Ointment IP 0.1%   10 GM for repigmentation in vitiligo and plaque eczema relief.",
    image: "/products/tacrovin-forte-10g.png",
    ingredients: ["Tacrolimus Ointment IP 0.1%  "],
    benefits: ["Promotes melanocyte migration", "Relieves chronic inflammation"],
    genericName: "Tacrolimus 0.1% Ointment",
    division: "Dermatology",
    dosageForm: "Ointment",
    strength: "10 GM",
    composition: "Tacrolimus Ointment IP - 0.1%  ",
    packaging: "10 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Vitiligo macules", "Atopic dermatitis"]
  },
  {
    id: "tacrovin-forte-ointment",
    name: "TACROVIN FORTE OINTMENT",
    category: "Skin Therapy & Wellness",
    tagline: "Extended-pack calcineurin ointment",
    description: "Tacrolimus IP 0.1%   30 GM ointment pack for long-term maintenance in widespread vitiligo patches.",
    image: "/products/tacrovin-forte-oint.png",
    ingredients: ["Tacrolimus IP 0.1%  "],
    benefits: ["Sustained repigmentation therapy", "Safe for delicate facial skin"],
    genericName: "Tacrolimus 0.1% Ointment",
    division: "Dermatology",
    dosageForm: "Ointment",
    strength: "30 GM",
    composition: "Tacrolimus IP - 0.1%  ",
    packaging: "30 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Facial & body vitiligo", "Eczema"]
  },
  {
    id: "tacrovin-lotion",
    name: "TACROVIN LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "Targeted topical calcineurin inhibitor lotion",
    description: "Tacrolimus Lotion IP 0.03% formulated for sensitive skin areas, scalp dermatoses, and vitiligo.",
    image: "/products/tacrovin-lotion.png",
    ingredients: ["Tacrolimus Lotion IP 0.03%"],
    benefits: ["Non-steroidal anti-inflammatory action", "Soothes flare-ups without steroid atrophy"],
    genericName: "Tacrolimus 0.03% Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "20 ML",
    composition: "Tacrolimus Lotion IP - 0.03%",
    packaging: "20 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Atopic dermatitis", "Vitiligo", "Facial & scalp eczema"],
    featured: true
  },
  {
    id: "tacrovin-ointment",
    name: "TACROVIN OINTMENT",
    category: "Skin Therapy & Wellness",
    tagline: "Maintenance calcineurin inhibitor ointment",
    description: "Tacrolimus Ointment IP 0.03%   30 GM for sensitive skin areas and mild atopic eczema maintenance.",
    image: "/products/tacrovin-oint.png",
    ingredients: ["Tacrolimus Ointment IP 0.03%  "],
    benefits: ["Prevents eczema relapses", "Gentle non-steroidal action"],
    genericName: "Tacrolimus 0.03% Ointment",
    division: "Dermatology",
    dosageForm: "Ointment",
    strength: "30 GM",
    composition: "Tacrolimus Ointment IP - 0.03%  ",
    packaging: "30 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Mild eczema maintenance", "Intertriginous vitiligo"]
  },
  {
    id: "galvate-lotion",
    name: "GALVATE LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "Potent anti-inflammatory corticosteroid lotion",
    description: "Beclomethasone Dipropionate 0.05%  lotion for controlling inflammatory scalp dermatoses.",
    image: "/products/galvate-lotion.png",
    ingredients: ["Beclomethasone Dipropionate 0.05% "],
    benefits: ["Rapidly reduces erythema", "Calms intense inflammation"],
    genericName: "Beclomethasone Dipropionate 0.05% Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "50 ML",
    composition: "Beclomethasone Dipropionate - 0.05% ",
    packaging: "50 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Psoriasis of the scalp", "Severe seborrheic dermatitis"]
  },
  {
    id: "galvate-c-lotion",
    name: "GALVATE-C LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "Combined corticosteroid & antifungal lotion",
    description: "Beclomethasone Dipropionate 0.025% and Clotrimazole 1% lotion for inflamed fungal and yeast skin infections.",
    image: "/products/galvate-c.png",
    ingredients: ["Beclomethasone Dipropionate IP 0.025% ", "Clotrimazole 1% "],
    benefits: ["Treats fungal infection while subduing redness", "Rapid symptom relief"],
    genericName: "Beclomethasone & Clotrimazole Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "30 ML",
    composition: "Beclomethasone Dipropionate IP - 0.025% , Clotrimazole - 1% ",
    packaging: "30 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Fungal dermatosis with eczema", "Candidal intertrigo"]
  },
  {
    id: "nuvate-s-lotion",
    name: "NUVATE-S LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "Super-potent keratolytic & steroid lotion",
    description: "Clobetasol Propionate 0.05% w/v & Salicylic Acid 3.0% w/v lotion designed for hyperkeratotic skin conditions and plaque psoriasis.",
    image: "/products/nuvate-s-lotion.jpg",
    ingredients: ["Clobetasol Propionate IP 0.05% w/v", "Salicylic Acid IP 3.0% w/v"],
    benefits: ["Keratolytic scale removal", "Deep anti-inflammatory action", "Promotes smooth skin renewal"],
    genericName: "Clobetasol Propionate & Salicylic Acid Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "30 ML",
    composition: "Clobetasol Propionate IP 0.05% w/v + Salicylic Acid IP 3.0% w/v",
    packaging: "30 ML Bottle",
    storage: "Store in a cool & dry place. Protect from light. Do not freeze.",
    indications: ["Plaque psoriasis", "Lichen planus", "Scalp hyperkeratosis"]
  },
  {
    id: "nuvate-s6-lotion",
    name: "NUVATE-S6 LOTION",
    category: "Skin Therapy & Wellness",
    tagline: "High-keratolytic chronic plaque lotion",
    description: "Clobetasol Propionate 0.05% w/v with Salicylic Acid 6% w/v for thick, recalcitrant psoriatic plaques and stubborn hyperkeratosis.",
    image: "/products/nuvate-s6-lotion.jpg",
    ingredients: ["Clobetasol Propionate IP 0.05% w/v", "Salicylic Acid IP 6% w/v"],
    benefits: ["Dissolves heavy hyperkeratotic scales", "Maximum topical penetration", "Intense anti-inflammatory relief"],
    genericName: "Clobetasol Propionate & Salicylic Acid Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "30 ML",
    composition: "Clobetasol Propionate IP 0.05% w/v + Salicylic Acid IP 6% w/v",
    packaging: "30 ML Bottle",
    storage: "Store in a cool & dry place. Protect from light. Do not freeze.",
    indications: ["Thick recalcitrant psoriatic plaques", "Severe palmaplantar keratoderma"]
  },
  {
    id: "mts-cream",
    name: "MTS CREAM",
    category: "Skin Therapy & Wellness",
    tagline: "Medium-potency anti-inflammatory cream",
    description: "Mometasone Furoate IP 0.1%   once-daily cream for effective treatment of steroid-responsive dermatoses.",
    image: "/products/MTS-cream.png",
    ingredients: ["Mometasone Furoate IP 0.1%  "],
    benefits: ["Once-daily application convenience", "High therapeutic index with low systemic absorption"],
    genericName: "Mometasone Furoate 0.1% Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "20 GM",
    composition: "Mometasone Furoate IP - 0.1%  ",
    packaging: "20 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Atopic dermatitis", "Allergic contact dermatitis", "Psoriasis"]
  },
  {
    id: "mts-f-cream",
    name: "MTS-F CREAM",
    category: "Skin Therapy & Wellness",
    tagline: "Anti-inflammatory & antibacterial combination cream",
    description: "Mometasone Furoate 0.1% and Fusidic Acid 2% cream for infected steroid-responsive inflammatory skin lesions.",
    image: "/products/mts-f-cream.png",
    ingredients: ["Mometasone Furoate IP 0.1%  ", "Fusidic Acid IP 2%  "],
    benefits: ["Combats bacterial pathogens while suppressing eczema flares"],
    genericName: "Mometasone & Fusidic Acid Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "10 GM",
    composition: "Mometasone Furoate IP - 0.1%   + Fusidic Acid IP - 2%  ",
    packaging: "10 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Infected eczematous dermatitis", "Secondary bacterial dermatosis"]
  },

  {
    id: "azaprin-tab",
    name: "AZAPRIN TAB",
    category: "Skin Therapy & Wellness",
    tagline: "Systemic purine synthesis inhibitor",
    description: "Azathioprine IP 50 mg oral tablets for steroid-sparing immunosuppression in severe refractory dermatoses.",
    image: "/products/azaprin-tab.png",
    ingredients: ["Azathioprine IP 50 mg"],
    benefits: ["Potent T-cell suppression", "Steroid-sparing oral option"],
    genericName: "Azathioprine 50 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Azathioprine IP - 50 mg",
    packaging: "10 Tablets Strip",
    storage: "Store protected from light.",
    indications: ["Severe chronic eczema", "Pemphigus vulgaris", "Systemic lupus erythematosus"]
  },
  {
    id: "jakshine-11-tablets",
    name: "JAKSHINE-11 TABLETS",
    category: "Skin Therapy & Wellness",
    tagline: "High-dose targeted Janus Kinase (JAK) inhibitor",
    description: "Tofacitinib Citrate IP 11 mg extended-release tablets for advanced systemic inhibition of inflammatory cytokines.",
    image: "/products/jakshine-11-tab.png",
    ingredients: ["Tofacitinib Citrate IP 11 mg"],
    benefits: ["Blocks JAK-1 & JAK-3 signaling pathways", "Rapid symptom reduction in severe dermatosis"],
    genericName: "Tofacitinib Citrate 11 mg ER Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Tofacitinib Citrate IP - 11 mg",
    packaging: "10 Tablets Strip",
    storage: "Store below 25°C.",
    indications: ["Alopecia areata", "Severe recalcitrant psoriasis", "Atopic dermatitis"]
  },
  {
    id: "jakshine-5-tablets",
    name: "JAKSHINE-5 TABLETS",
    category: "Skin Therapy & Wellness",
    tagline: "Targeted JAK pathway inhibitor",
    description: "Tofacitinib Citrate IP 5 mg oral tablets for targeted cytokine regulation in autoimmune skin conditions.",
    image: "/products/jakshine-5-tab.png",
    ingredients: ["Tofacitinib Citrate IP 5 mg"],
    benefits: ["Targeted immunomodulation", "Fades systemic inflammatory signals"],
    genericName: "Tofacitinib Citrate 5 mg Tablets",
    division: "Dermatology",
    dosageForm: "Tablets",
    strength: "1X10",
    composition: "Tofacitinib Citrate IP - 5 mg",
    packaging: "10 Tablets Strip",
    storage: "Store below 25°C.",
    indications: ["Vitiligo repigmentation protocol", "Psoriatic arthritis"]
  },
  {
    id: "sorigo-100-sg-capsule",
    name: "SORIGO 100 SG CAPSULE",
    category: "Skin Therapy & Wellness",
    tagline: "High-potency microemulsion Cyclosporine capsule",
    description: "Cyclosporine IP 100 mg soft gelatin capsules for rapid remission induction in severe plaque psoriasis flares.",
    image: "/products/sorigo-100.png",
    ingredients: ["Cyclosporine IP 100 mg"],
    benefits: ["Rapid suppression of active plaque formation", "High bioavailability microemulsion"],
    genericName: "Cyclosporine 100 mg Soft Gelatin Capsules",
    division: "Dermatology",
    dosageForm: "Capsules",
    strength: "1X6",
    composition: "Cyclosporine IP - 100 mg",
    packaging: "6 Softgel Capsules Strip",
    storage: "Store below 25°C. Do not freeze.",
    indications: ["Severe intractable psoriasis", "Severe acute atopic dermatitis"]
  },
  {
    id: "sorigo-50-sg-capsule",
    name: "SORIGO 50 SG CAPSULE",
    category: "Skin Therapy & Wellness",
    tagline: "Standard Cyclosporine microemulsion capsule",
    description: "Cyclosporine IP 50 mg soft gelatin capsules for dose titration and maintenance in autoimmune dermatoses.",
    image: "/products/sorigo-50-cap.png",
    ingredients: ["Cyclosporine IP 50 mg"],
    benefits: ["Controlled calcineurin pathway suppression", "Titratable dosage"],
    genericName: "Cyclosporine 50 mg Soft Gelatin Capsules",
    division: "Dermatology",
    dosageForm: "Capsules",
    strength: "1X6",
    composition: "Cyclosporine IP - 50 mg",
    packaging: "6 Softgel Capsules Strip",
    storage: "Store below 25°C.",
    indications: ["Psoriasis maintenance therapy", "Chronic dermatosis"]
  },

  {
    id: "ivernol-cream",
    name: "IVERNOL CREAM",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Targeted topical antiparasitic cream",
    description: "Ivermectin IP 1%   cream providing fast-acting anti-parasitic and anti-inflammatory relief for scabies and rosacea.",
    image: "/products/ivernol-cream.png",
    ingredients: ["Ivermectin IP 1%  "],
    benefits: ["Eradicates Sarcoptes scabiei mites", "Reduces inflammatory papules"],
    genericName: "Ivermectin 1% Cream",
    division: "Dermatology",
    dosageForm: "Cream",
    strength: "30 GM",
    composition: "Ivermectin IP - 1%  ",
    packaging: "30 GM Tube",
    storage: "Store below 25°C.",
    indications: ["Scabies infestation", "Papulopustular rosacea"]
  },
  {
    id: "ivernol-lotion",
    name: "IVERNOL LOTION",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Fluid antiparasitic body lotion",
    description: "Ivermectin IP 1%  lotion formulated for easy full-body application in scabies eradication programs.",
    image: "/products/ivernol-lotion.png",
    ingredients: ["Ivermectin IP 1% "],
    benefits: ["Easy full-body coverage", "Single application efficacy"],
    genericName: "Ivermectin 1% Lotion",
    division: "Dermatology",
    dosageForm: "Lotion",
    strength: "30 ML",
    composition: "Ivermectin IP - 1% ",
    packaging: "30 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Human scabies infection", "Demodex folliculorum mite overload"]
  },
  {
    id: "ivernol-sampoo",
    name: "IVERNOL SAMPOO",
    category: "Skin Infections & Anti-Fungal",
    tagline: "Pediculicidal scalp shampoo",
    description: "Ivermectin Scalp IP 0.5%  therapeutic shampoo for single-wash treatment of head lice (Pediculosis capitis).",
    image: "/products/ivernol-shampoo.png",
    ingredients: ["Ivermectin Scalp IP 0.5% "],
    benefits: ["Kills lice and nits", "10-minute application time", "Conditioning base"],
    genericName: "Ivermectin 0.5% Scalp Shampoo",
    division: "Dermatology",
    dosageForm: "Shampoo",
    strength: "30 ML",
    composition: "Ivermectin Scalp IP - 0.5% ",
    packaging: "30 ML Bottle",
    storage: "Store below 25°C.",
    indications: ["Pediculosis capitis (head lice)", "Scalp parasite infestation"]
  }
]
